import { Header } from "@/components/Header";
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";
import LocalFont from "next/font/local";
import React from 'react';
import "./globals.css";

const telegraf = LocalFont({
  src: [
    {
      path: "../fonts/PPTelegraf-UltraLight.otf",
    },
    {
      path: "../fonts/PPTelegraf-Regular.otf",
    },
   
  ], variable: "--font-telegraf"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <ClerkProvider>
      <html lang="en" className={telegraf.className}>

        <body>
          <Header />
          {children}
          <Toaster />

        </body>
      </html>
    </ClerkProvider>
  );
}
